baseurl                  = "https://example.com"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Call me Sam"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true



[[params.mainMenu]]
    link = "hiimigor"
    text = "Hi, I'm Igor."

[[params.mainMenu]]
    link = "goals"
    text = "goals."

[[params.mainMenu]]
    link = "achievementshub"
    text = "achievements."

[[params.mainMenu]]
    link = "airesearch"
    text = "AI research."

[[params.mainMenu]]
    link = "awards"
    text = "awards & certificates."

[[params.mainMenu]]
    link = "contact"
    text = "contact."
